# Generated by Django 4.1.7 on 2023-02-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sizes',
            field=models.JSONField(default=dict),
        ),
    ]
