# Generated by Django 4.1.7 on 2023-02-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sizes',
        ),
    ]
