# Generated by Django 4.1.7 on 2023-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sizes',
            field=models.CharField(default='', help_text='Comma separated list of zies', max_length=200),
        ),
    ]
