# Generated by Django 4.1.7 on 2023-02-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sizes',
            field=models.CharField(default='', help_text="Comma separated list of heights (e.g. '100,200')", max_length=200),
        ),
    ]
